fix
Signed-off-by: wangli <wangli858794774@gmail.com>

diff --git a/.github/workflows/image_build_and_push.yaml b/.github/workflows/image_build_and_push.yaml
--- a/.github/workflows/image_build_and_push.yaml
+++ b/.github/workflows/image_build_and_push.yaml
@@ -47,7 +47,7 @@ on:
 # only cancel in-progress runs of the same workflow
 concurrency:
   group: ${{ github.workflow }}-${{ github.ref }}
-  cancel-in-progress: ${{ github.event_name == 'pull_request' }}
+  cancel-in-progress: true
 
 jobs:
   build-push-digest:
@@ -57,13 +57,13 @@ jobs:
     strategy:
       matrix:
         include:
-          - arch: x86_64
+          - arch: linux/amd64
             runner: ubuntu-latest
-          - arch: aarch64
+          - arch: linux/arm64
             runner: ubuntu-22.04-arm
     if: ${{ github.event_name == 'push' }}
     steps:
-    - uses: actions/checkout@v6.0.1
+    - uses: actions/checkout@v4
       with:
         fetch-depth: 0
         persist-credentials: false
@@ -89,7 +89,7 @@ jobs:
             type=ref,event=pr
             type=pep440,pattern={{raw}}
         flavor:
-          latest=true
+          latest=false
 
     - name: Free up disk space
       uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be # v1.3.1
@@ -136,77 +136,77 @@ jobs:
         retention-days: 1
 
 
-  push-image:
-    runs-on: ubuntu-latest
-    needs: build-push-digest
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
+  # push-image:
+  #   runs-on: ubuntu-latest
+  #   needs: build-push-digest
+  #   steps:
+  #     - name: Checkout
+  #       uses: actions/checkout@v4
 
-      - name: Download digests
-        uses: actions/download-artifact@v4
-        with:
-          path: ${{ runner.temp }}/digests
-          pattern: digests-${{ inputs.cann_tag }}-*
-          merge-multiple: true
+  #     - name: Download digests
+  #       uses: actions/download-artifact@v4
+  #       with:
+  #         path: ${{ runner.temp }}/digests
+  #         pattern: digests-${{ inputs.cann_tag }}-*
+  #         merge-multiple: true
 
-      - name: Login to Quay
-        uses: docker/login-action@v3
-        with:
-          registry: quay.io
-          username: ${{ secrets.QUAY_USERNAME }}
-          password: ${{ secrets.QUAY_TOKEN }}
+  #     - name: Login to Quay
+  #       uses: docker/login-action@v3
+  #       with:
+  #         registry: quay.io
+  #         username: ${{ secrets.QUAY_USERNAME }}
+  #         password: ${{ secrets.QUAY_TOKEN }}
 
-      - name: Login to DockerHub
-        uses: docker/login-action@v3
-        with:
-          registry: docker.io
-          username: ${{ secrets.DOCKER_USERNAME }}
-          password: ${{ secrets.DOCKER_TOKEN }}
+  #     - name: Login to DockerHub
+  #       uses: docker/login-action@v3
+  #       with:
+  #         registry: docker.io
+  #         username: ${{ secrets.DOCKER_USERNAME }}
+  #         password: ${{ secrets.DOCKER_TOKEN }}
 
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v3
+  #     - name: Set up Docker Buildx
+  #       uses: docker/setup-buildx-action@v3
 
-      - name: Prepare tags
-        id: prepare-tags
-        run: |
-          BASE_TAGS=$(jq -r --arg cann_tag "${{ inputs.cann_tag }}" \
-            '.versions[] | select(.path == "cann/" + $cann_tag) | .tags[]' \
-            cann_publish_version.json)
-          registries=(
-            "docker.io/ascendai/cann"
-            "quay.io/ascend/cann"
-          )
-          first=true
-          TAGS_JSON="["
-          for registry in "${registries[@]}"; do
-            for tag in $(echo "$BASE_TAGS" | tr ',' ' '); do
-              if [ "$first" != true ]; then
-                TAGS_JSON+=","
-              fi
-              TAGS_JSON+="\"${registry}:${tag}\""
-              first=false
-            done
-          done
-          TAGS_JSON+="]"
-          echo "tags=${TAGS_JSON}" >> $GITHUB_OUTPUT
+  #     - name: Prepare tags
+  #       id: prepare-tags
+  #       run: |
+  #         BASE_TAGS=$(jq -r --arg cann_tag "${{ inputs.cann_tag }}" \
+  #           '.versions[] | select(.path == "cann/" + $cann_tag) | .tags[]' \
+  #           cann_publish_version.json)
+  #         registries=(
+  #           "docker.io/ascendai/cann"
+  #           "quay.io/ascend/cann"
+  #         )
+  #         first=true
+  #         TAGS_JSON="["
+  #         for registry in "${registries[@]}"; do
+  #           for tag in $(echo "$BASE_TAGS" | tr ',' ' '); do
+  #             if [ "$first" != true ]; then
+  #               TAGS_JSON+=","
+  #             fi
+  #             TAGS_JSON+="\"${registry}:${tag}\""
+  #             first=false
+  #           done
+  #         done
+  #         TAGS_JSON+="]"
+  #         echo "tags=${TAGS_JSON}" >> $GITHUB_OUTPUT
 
-      - name: Create manifest list and push
-        working-directory: ${{ runner.temp }}/digests
-        env:
-          TAGS: ${{ steps.prepare-tags.outputs.tags }}
-        run: |
-          readarray -t TAGS_ARRAY <<< "$(echo "$TAGS" | jq -r '.[]')"
+  #     - name: Create manifest list and push
+  #       working-directory: ${{ runner.temp }}/digests
+  #       env:
+  #         TAGS: ${{ steps.prepare-tags.outputs.tags }}
+  #       run: |
+  #         readarray -t TAGS_ARRAY <<< "$(echo "$TAGS" | jq -r '.[]')"
 
-          for TAG in "${TAGS_ARRAY[@]}"; do
-            if [[ "$TAG" == *"quay.io/ascend/cann"* ]]; then
-              docker buildx imagetools create -t "$TAG" \
-                $(printf 'quay.io/ascend/cann@sha256:%s ' *)
-            elif [[ "$TAG" == *"docker.io/ascendai/cann"* ]]; then
-              docker buildx imagetools create -t "$TAG" \
-                $(printf 'docker.io/ascendai/cann@sha256:%s ' *)
-            else
-              echo "Error: Unknown registry in TAG: $TAG"
-              exit 1
-            fi
-          done
+  #         for TAG in "${TAGS_ARRAY[@]}"; do
+  #           if [[ "$TAG" == *"quay.io/ascend/cann"* ]]; then
+  #             docker buildx imagetools create -t "$TAG" \
+  #               $(printf 'quay.io/ascend/cann@sha256:%s ' *)
+  #           elif [[ "$TAG" == *"docker.io/ascendai/cann"* ]]; then
+  #             docker buildx imagetools create -t "$TAG" \
+  #               $(printf 'docker.io/ascendai/cann@sha256:%s ' *)
+  #           else
+  #             echo "Error: Unknown registry in TAG: $TAG"
+  #             exit 1
+  #           fi
+  #         done
